# Generated by Django 4.1.1 on 2022-10-11 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='staff_rank',
            field=models.CharField(blank=True, choices=[('Trainee', 'Trainee'), ('Ninja', 'Ninja'), ('Ronin', 'Ronin'), ('Samurai', 'Samurai'), ('Daimio', 'Daimio')], max_length=20, null=True, verbose_name='Ранг'),
        ),
    ]
