# Generated by Django 4.1.1 on 2022-10-10 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='mentor_status_evening',
            field=models.BooleanField(default=False),
        ),
    ]
