# Generated by Django 4.1.4 on 2022-12-07 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_staff_staff_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='name',
            field=models.CharField(max_length=50, verbose_name='name'),
        ),
    ]
