# Generated by Django 4.1.4 on 2022-12-07 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_alter_staff_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='staff_rank',
            field=models.CharField(blank=True, choices=[('Trainee', 'Trainee'), ('Ninja', 'Ninja'), ('Ronin', 'Ronin'), ('Samurai', 'Samurai'), ('Daimio', 'Daimio')], max_length=20, null=True, verbose_name='Rang'),
        ),
    ]
