# Generated by Django 4.0.8 on 2022-12-20 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_alter_staff_staff_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='staff',
            name='name',
            field=models.CharField(max_length=50, verbose_name='имя'),
        ),
    ]
