<<<<<<< HEAD
# Generated by Django 4.1.1 on 2022-10-04 09:21
=======
# Generated by Django 4.1.1 on 2022-10-04 06:08
>>>>>>> f3452207bd0d64f6ee14b6fd6ef364c4512547ac

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('group', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('room_name', models.IntegerField()),
=======
                ('room_number', models.IntegerField()),
>>>>>>> f3452207bd0d64f6ee14b6fd6ef364c4512547ac
                ('capacity', models.IntegerField()),
                ('room_status', models.BooleanField(default=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='group.group')),
                ('mentor', models.ForeignKey(default='кабинет свободен', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='rooms', to='staff.staff')),
            ],
            options={
                'verbose_name': 'Кабинет',
                'verbose_name_plural': 'Кабинеты',
            },
        ),
    ]
