# Generated by Django 4.1.1 on 2022-10-04 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.IntegerField()),
                ('capacity', models.IntegerField()),
                ('room_status', models.BooleanField(default=False)),
                ('mentor', models.ForeignKey(default='кабинет свободен', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='rooms', to='staff.staff')),
            ],
            options={
                'verbose_name': 'Кабинет',
                'verbose_name_plural': 'Кабинеты',
            },
        ),
    ]
