# Generated by Django 4.1.1 on 2022-10-04 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_group_amount_alter_group_group_studying_time'),
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='group',
            field=models.ForeignKey(default='кабинет свободен', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='rooms', to='group.group'),
        ),
    ]
