# Generated by Django 4.1.1 on 2022-10-05 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_alter_room_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'Кабинеты', 'verbose_name_plural': 'Кабинеты'},
        ),
        migrations.RenameField(
            model_name='room',
            old_name='room_status',
            new_name='room_status_day',
        ),
        migrations.AddField(
            model_name='room',
            name='room_status_evening',
            field=models.BooleanField(default=False),
        ),
    ]
