# Generated by Django 4.1.1 on 2022-10-04 13:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='amount',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(36), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_studying_time',
            field=models.CharField(choices=[('day', 'дневная'), ('evening', 'вечерняя')], max_length=20),
        ),
    ]
