# Generated by Django 4.1.1 on 2022-10-12 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='is_graduated',
            field=models.BooleanField(default=False),
        ),
    ]
