# Generated by Django 4.1.1 on 2022-10-11 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='date_of_start',
            field=models.DateField(blank=True, choices=[], null=True),
        ),
    ]
